excluded:
- Pods
- MBUITest

disabled_rules:
- trailing_whitespace
- nesting

function_parameter_count:
 warning: 10
 error: 15

line_length: 160

file_length:
 warning: 500

type_body_length:
 warning: 400
